export const LANGUAGES = ["C++", "C", "Python", "Java", "JS"];
export const NUM_AVATARS = 5;
export const VALID_PHONE_NUMBER = /^\+?[1-9]\d{1,14}$/; // E.164 phone format
export const MAX_CHARS_TITLE_DESCRIPTION = 500;
export const MAX_CHARS_CONTENT = 10000;
export const MIN_CHARS = 1;
export const MAX_CHARS_TAG = 50;
export const SERVER_ERROR_MSG = "Internal Server Error";
export const MIN_PAGES = 1;
export const MIN_PAGE_SIZE = 1;
export const MAX_PAGE_SIZE = 100;
export const MAX_PAGES = 100;
export const PAGE_SIZE = 10;